steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'us-docker.pkg.dev/${PROJECT_ID}/nextjs-frontend/nextjs-frontend:latest', './frontend']
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'us-docker.pkg.dev/${PROJECT_ID}/nextjs-frontend/nextjs-frontend:latest']
- name: 'gcr.io/cloud-builders/gcloud'
  entrypoint: 'bash'
  args:
  - '-c'
  - |
    gcloud run deploy mimir-frontend \
    --image us-docker.pkg.dev/${PROJECT_ID}/nextjs-frontend/nextjs-frontend:latest \
    --region us-central1 \
    --allow-unauthenticated \
    --port 3000 \
    --set-secrets=NEXT_PUBLIC_BACKEND_IP=NEXT_PUBLIC_BACKEND_IP:latest \
  secretEnv: ['NEXT_PUBLIC_BACKEND_IP']

availableSecrets:
  secretManager:
  - versionName: projects/${PROJECT_ID}/secrets/NEXT_PUBLIC_BACKEND_IP/versions/latest
    env: 'NEXT_PUBLIC_BACKEND_IP'

options:
  logging: CLOUD_LOGGING_ONLY
