package models

type Incident struct {
	PromotedBy             string     `json:"promoted_by"`
	Parent                 string     `json:"parent"`
	CausedBy               string     `json:"caused_by"`
	WatchList              string     `json:"watch_list"`
	UponReject             string     `json:"upon_reject"`
	SysUpdatedOn           string     `json:"sys_updated_on"`
	OriginTable            string     `json:"origin_table"`
	ApprovalHistory        string     `json:"approval_history"`
	Number                 string     `json:"number"`
	ProposedBy             string     `json:"proposed_by"`
	UGender                string     `json:"u_gender"`
	LessonsLearned         string     `json:"lessons_learned"`
	State                  string     `json:"state"`
	SysCreatedBy           string     `json:"sys_created_by"`
	Knowledge              string     `json:"knowledge"`
	Order                  string     `json:"order"`
	CmdbCI                 string     `json:"cmdb_ci"`
	DeliveryPlan           string     `json:"delivery_plan"`
	Contract               string     `json:"contract"`
	Impact                 string     `json:"impact"`
	Active                 string     `json:"active"`
	WorkNotesList          string     `json:"work_notes_list"`
	Priority               string     `json:"priority"`
	SysDomainPath          string     `json:"sys_domain_path"`
	BusinessDuration       string     `json:"business_duration"`
	GroupList              string     `json:"group_list"`
	ApprovalSet            string     `json:"approval_set"`
	MajorIncidentState     string     `json:"major_incident_state"`
	UniversalRequest       string     `json:"universal_request"`
	ShortDescription       string     `json:"short_description"`
	CorrelationDisplay     string     `json:"correlation_display"`
	DeliveryTask           string     `json:"delivery_task"`
	WorkStart              string     `json:"work_start"`
	TriggerRule            string     `json:"trigger_rule"`
	AdditionalAssigneeList string     `json:"additional_assignee_list"`
	Notify                 string     `json:"notify"`
	ServiceOffering        string     `json:"service_offering"`
	SysClassName           string     `json:"sys_class_name"`
	ClosedBy               string     `json:"closed_by"`
	FollowUp               string     `json:"follow_up"`
	ParentIncident         string     `json:"parent_incident"`
	ReopenedBy             string     `json:"reopened_by"`
	ReassignmentCount      string     `json:"reassignment_count"`
	AssignedTo             string     `json:"assigned_to"`
	SLADue                 string     `json:"sla_due"`
	CommentsAndWorkNotes   string     `json:"comments_and_work_notes"`
	Escalation             string     `json:"escalation"`
	UponApproval           string     `json:"upon_approval"`
	CorrelationID          string     `json:"correlation_id"`
	Timeline               string     `json:"timeline"`
	MadeSLA                string     `json:"made_sla"`
	PromotedOn             string     `json:"promoted_on"`
	ChildIncidents         string     `json:"child_incidents"`
	HoldReason             string     `json:"hold_reason"`
	TaskEffectiveNumber    string     `json:"task_effective_number"`
	ResolvedBy             string     `json:"resolved_by"`
	SysUpdatedBy           string     `json:"sys_updated_by"`
	OpenedBy               LinkObject `json:"opened_by"`
	UserInput              string     `json:"user_input"`
	SysCreatedOn           string     `json:"sys_created_on"`
	SysDomain              LinkObject `json:"sys_domain"`
	ProposedOn             string     `json:"proposed_on"`
	ActionsTaken           string     `json:"actions_taken"`
	RouteReason            string     `json:"route_reason"`
	CalendarSTC            string     `json:"calendar_stc"`
	ClosedAt               string     `json:"closed_at"`
	BusinessService        string     `json:"business_service"`
	BusinessImpact         string     `json:"business_impact"`
	RFC                    string     `json:"rfc"`
	TimeWorked             string     `json:"time_worked"`
	ExpectedStart          string     `json:"expected_start"`
	OpenedAt               string     `json:"opened_at"`
	WorkEnd                string     `json:"work_end"`
	CallerID               LinkObject `json:"caller_id"`
	ReopenedTime           string     `json:"reopened_time"`
	ResolvedAt             string     `json:"resolved_at"`
	Subcategory            string     `json:"subcategory"`
	WorkNotes              string     `json:"work_notes"`
	CloseCode              string     `json:"close_code"`
	AssignmentGroup        string     `json:"assignment_group"`
	BusinessSTC            string     `json:"business_stc"`
	Cause                  string     `json:"cause"`
	Description            string     `json:"description"`
	OriginID               string     `json:"origin_id"`
	CalendarDuration       string     `json:"calendar_duration"`
	CloseNotes             string     `json:"close_notes"`
	SysID                  string     `json:"sys_id"`
	ContactType            string     `json:"contact_type"`
	IncidentState          string     `json:"incident_state"`
	Urgency                string     `json:"urgency"`
	ProblemID              string     `json:"problem_id"`
	Company                string     `json:"company"`
	ActivityDue            string     `json:"activity_due"`
	Severity               string     `json:"severity"`
	Overview               string     `json:"overview"`
	Comments               string     `json:"comments"`
	Approval               string     `json:"approval"`
	DueDate                string     `json:"due_date"`
	SysModCount            string     `json:"sys_mod_count"`
	ReopenCount            string     `json:"reopen_count"`
	SysTags                string     `json:"sys_tags"`
	Location               string     `json:"location"`
	Category               string     `json:"category"`
}

type LinkObject struct {
	Link  string `json:"link"`
	Value string `json:"value"`
}

type ApiResponse struct {
	Result []Incident `json:"result"`
}
